version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/**"
    registries:
      - github-npm-registry
    schedule:
      interval: daily
      time: "03:00"
      timezone: "Europe/London"
    cooldown:
      default-days: 7
    labels:
      - dependabot
      - dependencies
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"
    commit-message:
      prefix: BAU
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
      timezone: "Europe/London"
    cooldown:
      default-days: 7
    labels:
      - dependabot
      - dependencies
    commit-message:
      prefix: BAU

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
      timezone: "Europe/London"
    cooldown:
      default-days: 7
    labels:
      - dependabot
      - dependencies
    commit-message:
      prefix: BAU

  - package-ecosystem: "terraform"
    directory: "/solutions/infra"
    schedule:
      interval: daily
      time: "03:00"
      timezone: "Europe/London"
    cooldown:
      default-days: 7
    labels:
      - dependabot
      - dependencies
    commit-message:
      prefix: BAU

  - package-ecosystem: docker
    directories:
      - "/solutions/integration-tests"
      - "/solutions/localstack/local-kms"
      - "/solutions/localstack/localstack"
    schedule:
      interval: daily
      time: "03:00"
      timezone: "Europe/London"
    cooldown:
      default-days: 7
    labels:
      - dependabot
      - dependencies
    commit-message:
      prefix: BAU
    ignore:
      - dependency-name: "node"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "localstack/localstack"
        versions:
          - "> 4.12.0" # Can't be updated past the 4.12.0 due to localstack changing the licence

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
      timezone: "Europe/London"
    cooldown:
      default-days: 7
    labels:
      - dependabot
      - dependencies
    commit-message:
      prefix: BAU

registries:
  github-npm-registry:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.NODE_AUTH_TOKEN }}
