ignore_checks:
  - W1001 # GetAtt to resource that may not be available depending on a condition
  - W1028 # is not reachable
  - W8001 # Condition is not used
  - E3002 # TODO remove once https://github.com/aws/aws-sam-cli/issues/8465 is resolved sam v1.45.2
