import type { FastifyReply, FastifyRequest } from "fastify";

export function hello(_request: FastifyRequest, reply: FastifyReply) {
  return reply.send([
    {
      _id: "68b96f30e4bc6cc93fee399c",
      index: 0,
      guid: "496a3765-aa00-407f-8af4-fa9e60e96280",
      isActive: true,
      balance: "$1,466.92",
      picture: "http://placehold.it/32x32",
      age: 36,
      eyeColor: "brown",
      name: "Sharron Whitley",
      gender: "female",
      company: "ISOPLEX",
      email: "sharronwhitley@isoplex.com",
      phone: "+1 (992) 466-3638",
      address: "194 Schweikerts Walk, Swartzville, Massachusetts, 7429",
      about:
        "Minim duis aliqua amet cupidatat nisi. Aliquip pariatur proident nostrud incididunt ipsum labore aliquip. Eu consequat elit ipsum sint elit aute id occaecat occaecat fugiat ut laboris. Nostrud anim aute nisi esse cillum voluptate exercitation elit labore fugiat fugiat quis nulla dolor.\r\n",
      registered: "2017-09-10T09:55:14 -01:00",
      latitude: -20.580152,
      longitude: -88.433271,
      tags: [
        "ex",
        "exercitation",
        "irure",
        "officia",
        "velit",
        "officia",
        "officia",
      ],
      friends: [
        {
          id: 0,
          name: "Gilmore Travis",
        },
        {
          id: 1,
          name: "Hamilton Townsend",
        },
        {
          id: 2,
          name: "Gabrielle Payne",
        },
      ],
      greeting: "Hello, Sharron Whitley! You have 3 unread messages.",
      favoriteFruit: "apple",
    },
    {
      _id: "68b96f30f6d441a6e94c1a23",
      index: 1,
      guid: "e1de8014-bb56-4279-98bd-8c3b1f9589d4",
      isActive: true,
      balance: "$3,020.26",
      picture: "http://placehold.it/32x32",
      age: 36,
      eyeColor: "brown",
      name: "Lauren Horn",
      gender: "female",
      company: "MAROPTIC",
      email: "laurenhorn@maroptic.com",
      phone: "+1 (846) 497-3583",
      address: "156 Junius Street, Levant, Oklahoma, 6970",
      about:
        "Duis id id aliqua duis aliquip exercitation nostrud. Ullamco proident eu laboris Lorem adipisicing dolor qui nostrud voluptate ipsum cupidatat. Irure aute pariatur veniam ut ex commodo. Eu sit sunt laboris ad quis do est reprehenderit laborum dolor proident qui. Mollit eu commodo enim magna est amet ea est occaecat duis pariatur commodo adipisicing pariatur.\r\n",
      registered: "2015-02-09T11:21:11 -00:00",
      latitude: -77.344549,
      longitude: 159.39557,
      tags: ["aliqua", "anim", "eu", "mollit", "enim", "cupidatat", "Lorem"],
      friends: [
        {
          id: 0,
          name: "Deborah Finch",
        },
        {
          id: 1,
          name: "Molina Mckinney",
        },
        {
          id: 2,
          name: "Imogene Leblanc",
        },
      ],
      greeting: "Hello, Lauren Horn! You have 4 unread messages.",
      favoriteFruit: "apple",
    },
    {
      _id: "68b96f30d0e3217a4cb8ae9d",
      index: 2,
      guid: "341cb158-4ab7-46d7-be73-5a06b4e2a639",
      isActive: false,
      balance: "$1,501.29",
      picture: "http://placehold.it/32x32",
      age: 26,
      eyeColor: "brown",
      name: "Dyer Barnett",
      gender: "male",
      company: "SURETECH",
      email: "dyerbarnett@suretech.com",
      phone: "+1 (893) 521-3672",
      address: "833 Linden Street, Dorneyville, Northern Mariana Islands, 703",
      about:
        "Labore enim ipsum magna elit. Veniam pariatur cillum commodo consequat voluptate ipsum aliquip voluptate nisi minim eiusmod. Et aute deserunt culpa ea quis voluptate duis quis enim eu esse cupidatat veniam eu. Labore magna aliqua esse cillum do qui occaecat enim cillum fugiat duis esse.\r\n",
      registered: "2019-07-07T12:41:13 -01:00",
      latitude: -63.124632,
      longitude: 34.147515,
      tags: ["qui", "amet", "sint", "eu", "labore", "adipisicing", "magna"],
      friends: [
        {
          id: 0,
          name: "Bates Carpenter",
        },
        {
          id: 1,
          name: "Lilly Lamb",
        },
        {
          id: 2,
          name: "Marian Malone",
        },
      ],
      greeting: "Hello, Dyer Barnett! You have 5 unread messages.",
      favoriteFruit: "apple",
    },
    {
      _id: "68b96f301ebfd1551e18431b",
      index: 3,
      guid: "d0e2da01-f7fb-4b31-8763-edbc25a86434",
      isActive: true,
      balance: "$2,360.19",
      picture: "http://placehold.it/32x32",
      age: 21,
      eyeColor: "brown",
      name: "Krista Walsh",
      gender: "female",
      company: "UNEEQ",
      email: "kristawalsh@uneeq.com",
      phone: "+1 (850) 426-2500",
      address: "918 Greene Avenue, Templeton, Virgin Islands, 1653",
      about:
        "Culpa ut fugiat eu nulla. Laborum in dolor non et excepteur irure laboris sit est. Exercitation irure laborum excepteur occaecat amet irure id. Aliquip dolore ad adipisicing minim.\r\n",
      registered: "2020-10-02T10:23:17 -01:00",
      latitude: -19.551967,
      longitude: 91.534747,
      tags: ["id", "amet", "eu", "cillum", "aute", "non", "magna"],
      friends: [
        {
          id: 0,
          name: "Violet Oliver",
        },
        {
          id: 1,
          name: "Sharon Hansen",
        },
        {
          id: 2,
          name: "Case Carlson",
        },
      ],
      greeting: "Hello, Krista Walsh! You have 2 unread messages.",
      favoriteFruit: "strawberry",
    },
    {
      _id: "68b96f301e39d471550d0cba",
      index: 4,
      guid: "2e0c29a6-11bc-4ae4-a7ec-24e532f41c58",
      isActive: true,
      balance: "$1,449.50",
      picture: "http://placehold.it/32x32",
      age: 39,
      eyeColor: "brown",
      name: "Evans Sims",
      gender: "male",
      company: "ENAUT",
      email: "evanssims@enaut.com",
      phone: "+1 (820) 432-2030",
      address: "908 Williams Court, Elrama, Nebraska, 1029",
      about:
        "Elit ut adipisicing irure reprehenderit ea elit. Incididunt dolor labore enim enim dolore. Laboris dolor pariatur labore pariatur sint magna occaecat ad velit excepteur eu reprehenderit magna adipisicing. Ea in ea enim occaecat incididunt minim culpa non. Sint sint est pariatur magna non commodo quis est pariatur tempor incididunt sint nisi. Irure irure culpa est veniam consectetur ea sint excepteur nostrud.\r\n",
      registered: "2021-09-09T03:57:03 -01:00",
      latitude: 10.122951,
      longitude: -154.607455,
      tags: ["Lorem", "amet", "laborum", "cupidatat", "do", "ea", "ex"],
      friends: [
        {
          id: 0,
          name: "Spears Hernandez",
        },
        {
          id: 1,
          name: "Farmer Grant",
        },
        {
          id: 2,
          name: "Glover Bauer",
        },
      ],
      greeting: "Hello, Evans Sims! You have 9 unread messages.",
      favoriteFruit: "strawberry",
    },
    {
      _id: "68b96f307523ff114d8608a4",
      index: 5,
      guid: "0445beee-5515-442e-8ecc-e986114a5b79",
      isActive: false,
      balance: "$2,860.83",
      picture: "http://placehold.it/32x32",
      age: 20,
      eyeColor: "blue",
      name: "Terry Rocha",
      gender: "female",
      company: "QIMONK",
      email: "terryrocha@qimonk.com",
      phone: "+1 (985) 419-3655",
      address: "688 Norfolk Street, Saddlebrooke, Utah, 9148",
      about:
        "Fugiat eu occaecat culpa sit cupidatat proident. Dolore proident eu cupidatat voluptate sit veniam veniam eiusmod in. Incididunt labore ullamco ex id id sit.\r\n",
      registered: "2024-10-31T05:45:06 -00:00",
      latitude: -9.129522,
      longitude: -165.292459,
      tags: ["est", "tempor", "dolore", "exercitation", "aute", "do", "nisi"],
      friends: [
        {
          id: 0,
          name: "Rowe Wiley",
        },
        {
          id: 1,
          name: "Bridgette Mendez",
        },
        {
          id: 2,
          name: "Summer Sosa",
        },
      ],
      greeting: "Hello, Terry Rocha! You have 4 unread messages.",
      favoriteFruit: "banana",
    },
    {
      _id: "68b96f30fc71fb128432986c",
      index: 6,
      guid: "40141448-4f30-445e-a5ad-ba19e2a46bb5",
      isActive: false,
      balance: "$3,923.11",
      picture: "http://placehold.it/32x32",
      age: 31,
      eyeColor: "blue",
      name: "Barnes Padilla",
      gender: "male",
      company: "BLUEGRAIN",
      email: "barnespadilla@bluegrain.com",
      phone: "+1 (866) 567-2116",
      address: "497 Bush Street, Flintville, Colorado, 6924",
      about:
        "Non excepteur ea culpa occaecat do ullamco sunt nostrud consectetur nulla officia esse laboris adipisicing. Ipsum non in quis sit labore dolor. Sit mollit ad aliquip irure. Nostrud magna proident magna irure. Velit consectetur irure eiusmod non. Deserunt commodo voluptate occaecat proident dolore. Culpa pariatur et aliquip esse velit veniam consectetur ipsum.\r\n",
      registered: "2021-10-23T07:29:43 -01:00",
      latitude: 38.585048,
      longitude: -106.599005,
      tags: ["consequat", "occaecat", "velit", "laborum", "ut", "non", "id"],
      friends: [
        {
          id: 0,
          name: "Miranda Church",
        },
        {
          id: 1,
          name: "Wolf Morris",
        },
        {
          id: 2,
          name: "Hopper English",
        },
      ],
      greeting: "Hello, Barnes Padilla! You have 7 unread messages.",
      favoriteFruit: "strawberry",
    },
  ]);
}
