AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Creates a role that can be assumed by Github Actions

Parameters:
  GitHubOrg:
    Type: String
  RepositoryName:
    Type: String
  OIDCProviderArn:
    Description: Arn for the GitHub OIDC Provider.
    Default: ""
    Type: String

Conditions:
  CreateOIDCProvider: !Equals
    - !Ref OIDCProviderArn
    - ""

Resources:
  Role:
    Type: AWS::IAM::Role
    # checkov:skip=CKV_AWS_111: "Ensure IAM policies does not allow write access without constraints"
    # checkov:skip=CKV_AWS_109: "Ensure IAM policies does not allow permissions management without constraints"
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !If
                - CreateOIDCProvider
                - !Ref GithubOidc
                - !Ref OIDCProviderArn
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GitHubOrg}/${RepositoryName}:*
      Policies:
        - PolicyName: GitHubActions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Resource: "*"
                Action:
                  - iam:GetRole
                  - iam:TagRole
                  - iam:PassRole
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:ListPolicies
                  - iam:PutRolePolicy
                  - iam:GetRolePolicy
                  - iam:DeleteRolePolicy
                  - iam:AttachRolePolicy
                  - iam:DetachRolePolicy
                  - cloudformation:DescribeStacks

              - Effect: Allow
                Resource: "*"
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                  - s3:DeleteObject
                  - s3:PutBucketTagging

              - Effect: Allow
                Resource: "*"
                Action:
                  - ssm:PutParameter
                  - ssm:AddTagsToResource

              - Effect: Allow
                Resource:
                  - arn:aws:s3:::*
                Action:
                  - s3:CreateBucket
                  - s3:DeleteBucket
                  - s3:GetEncryptionConfiguration
                  - s3:PutEncryptionConfiguration
                  - s3:PutBucketVersioning
                  - s3:PutPublicAccessBlock
                  - s3:PutBucketPublicAccessBlock
                  - s3:PutBucketPolicy
                  - s3:GetBucketPolicy
                  - s3:GetBucketPolicyStatus
                  - s3:PutBucketTagging
                  - s3:DeleteBucketPolicy

              - Effect: Allow
                Resource: "*"
                Action:
                  - cloudformation:DeleteStack
                  - cloudformation:GetTemplate
                  - cloudformation:CreateChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:DescribeChangeSet
                  - cloudformation:GetTemplateSummary
                  - cloudformation:DescribeStackEvents

              - Effect: Allow
                Resource: "*"
                Action:
                  - kms:DescribeKey
                  - kms:DeleteAlias
                  - kms:TagResource
                  - kms:UntagResource
                  - kms:ListResourceTags
                  - kms:EnableKeyRotation
                  - kms:ScheduleKeyDeletion
                  - kms:PutKeyPolicy

              - Effect: Allow
                Resource: "*"
                Action:
                  - secretsmanager:CreateSecret #pragma: allowlist secret
                  - secretsmanager:TagResource #pragma: allowlist secret
                  - secretsmanager:DeleteSecret #pragma: allowlist secret
                  - secretsmanager:ResourcePolicy #pragma: allowlist secret
                  - secretsmanager:DeleteResourcePolicy #pragma: allowlist secret
                  - secretsmanager:PutResourcePolicy #pragma: allowlist secret

              - Effect: Allow
                Resource: "*"
                Action:
                  - kms:CreateKey
                  - kms:CreateAlias

              - Effect: Allow
                Resource: "*"
                Action:
                  - lambda:ListFunctions
                  - lambda:GetFunctionConfiguration
                  - lambda:UpdateFunctionConfiguration
                  - lambda:PublishVersion
                  - lambda:UpdateAlias

              - Effect: Allow
                Resource: "*"
                Action:
                  - ssm:DeleteParameter
                  - ssm:GetParameters
                  - ssm:RemoveTagsFromResource

              - Effect: Allow
                Resource: "*"
                Action:
                  - apigateway:*

              - Effect: Allow
                Resource: "*"
                Action:
                  - appconfig:*

  GithubOidc:
    Type: AWS::IAM::OIDCProvider
    Condition: CreateOIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1

Outputs:
  Role:
    Value: !GetAtt Role.Arn
