openapi: 3.0.3
info:
  version: 9.5.1
  title: "@fastify/swagger"
components:
  schemas: {}
paths:
  /api/hello:
    get:
      parameters:
        - schema:
            type: number
          in: query
          name: foo
          required: true
        - schema:
            type: string
          in: query
          name: bar
          required: true
      responses:
        "200":
          description: Default Response
  /api//:
    get:
      responses:
        "200":
          description: Default Response
  /html:
    get:
      responses:
        "200":
          description: Default Response
  /robots.txt:
    get:
      responses:
        "200":
          description: Default Response

