openapi: 3.0.3
info:
  version: 9.5.1
  title: "@fastify/swagger"
components:
  schemas: {}
paths:
  /private-healthcheck:
    get:
      tags:
        - include-in-docs
      responses:
        "200":
          description: Default Response

