openapi: 3.0.3
info:
  version: 9.5.1
  title: "@fastify/swagger"
components:
  schemas: {}
paths:
  /healthcheck:
    get:
      responses:
        "200":
          description: Default Response
  /robots.txt:
    get:
      responses:
        "200":
          description: Default Response
  /stubs/external-endpoints/:
    get:
      parameters:
        - schema:
            type: number
          in: query
          name: updated
          required: false
      responses:
        "200":
          description: Default Response
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                type: string
      responses:
        "200":
          description: Default Response
  /stubs/external-endpoints/temp-external-endpoint-stub-example:
    get:
      responses:
        "200":
          description: Default Response

