---
openapi: 3.0.3

info:
  title: Account Management Components OAuth Provider Private API
  version: 0.0.3
  description: |
    OAuth 2.0 provider endpoints, including:
    - POST /v1/token (supports client assertions via private_key_jwt)
    - GET /v1/journeyoutcome
    - GET /v1/.well-known/jwks.json (publishes signing and encryption keys)
    - GET /v1/.well-known/oauth-authorization-server (OAuth Discovery)
  contact:
    name: GDS - DI Accounts Pod - Home Team
    email: one-login-home-team@digital.cabinet-office.gov.uk
  license:
    name: MIT
    url: https://github.com/govuk-one-login/account-components/blob/main/LICENSE.md
tags:
  - name: OAuth
    description: |-
      Supporting methods for Account Management Component Journeys.

      **Note:** This functionality is intended to be used by systems solely belonging internally to GDS DI.
  - name: AMC
    description: |-
      Specific methods for Account Management Component Journeys.

      **Note:** This functionality is intended to be used by systems solely belonging internally to GDS DI.
servers:
  - url: https://abcd1234.execute-api.eu-west-2.amazonaws.com
    description: private development server
  - url: https://abcd1234.execute-api.eu-west-2.amazonaws.com
    description: private build server
  - url: https://abcd1234.execute-api.eu-west-2.amazonaws.com
    description: private staging server
  - url: https://abcd1234.execute-api.eu-west-2.amazonaws.com
    description: private integration server
  - url: https://abcd1234.execute-api.eu-west-2.amazonaws.com
    description: private production server

paths:
  /v1/token:
    post:
      summary: Token endpoint
      description: |
        Issues tokens for supported grants. This endpoint supports `private_key_jwt` client authentication via `client_assertion_type` and `client_assertion` per RFC 7523.
      operationId: token
      tags:
        - OAuth
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                grant_type:
                  type: string
                  enum:
                    - authorization_code
                  example: authorization_code
                code:
                  type: string
                  description: Required for `authorization_code`.
                  example: anAuthCode
                redirect_uri:
                  type: string
                  format: uri
                  description: Must be the same as in the authorize request.
                  pattern: ^(https|http)://(www\.)?((localhost(:[0-9]+)?)|[-a-zA-Z0-9@:%._+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b)([-a-zA-Z0-9()@:%_+.~#?&/=]*)$
                  example: https://signin.account.gov.uk/callbacks/account-deletion
                client_assertion_type:
                  type: string
                  enum:
                    ["urn:ietf:params:oauth:client-assertion-type:jwt-bearer"]
                  description: Indicates private_key_jwt authentication.
                client_assertion:
                  type: string
                  description: JWT signed by the client's private key.
              required:
                - grant_type
                - code
                - redirect_uri
                - client_assertion_type
                - client_assertion
      responses:
        "200":
          description: Token response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenResponse"
        "400":
          description: Invalid request or unsupported grant type.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OAuthError"
        "401":
          description: Invalid client assertion or unauthorized client.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OAuthError"

  /v1/journeyoutcome:
    get:
      summary: Journey Outcome endpoint
      description: Get Journey Outcome information
      security:
        - bearerAuth: []
      operationId: journeyoutcome
      tags:
        - AMC
      responses:
        "200":
          description: Claims about the outcome of the user's journey
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JourneyOutcome"
        "401":
          description: Missing or invalid access token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OAuthError"

  /v1/.well-known/jwks.json:
    get:
      summary: JSON Web Key Set (JWKS)
      description: Publishes public keys for signature and encryption.
      operationId: jwks
      tags:
        - OAuth
      responses:
        "200":
          description: JWK Set
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JWKSet"
              examples:
                example:
                  value:
                    keys:
                      - kty: RSA
                        use: enc
                        kid: enc-2025-01
                        alg: RSA-OAEP-256
                        n: "t7Z...base64url-modulus" # pragma: allowlist secret
                        e: "AQAB" # pragma: allowlist secret

  /v1/.well-known/oauth-authorization-server:
    get:
      summary: OAuth Provider Configuration (Discovery)
      description: Discover OAuth method URLs
      operationId: discovery
      tags:
        - OAuth
      responses:
        "200":
          description: OAuth discovery metadata document (rfc8414)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProviderConfiguration"
              examples:
                example:
                  value:
                    issuer: https://api.manage.account.gov.uk
                    authorization_endpoint: https://api.manage.account.gov.uk/authorize
                    token_endpoint: https://abcd1234.execute-api.eu-west-2.amazonaws.com/v1/token
                    jwks_uri: https://api.manage.account.gov.uk/.well-known/jwks.json
                    response_types_supported: [code]
                    token_endpoint_auth_methods_supported: [private_key_jwt]
                    token_endpoint_auth_signing_alg_values_supported: [RS256]
                    scopes_supported: [testing-journey, account-delete]
                    grant_types_supported: [authorization_code]

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    OAuthError:
      type: object
      properties:
        error:
          type: string
          description: Error code
          example: invalid_request
        error_description:
          type: string
          example: E9999
      required:
        - error

    TokenResponse:
      type: object
      properties:
        access_token:
          type: string
          example: eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6IjJhNjkzNjFkLTAzOTctNGU4OS04ZmFlLTI4YjFjMmZlZDYxNCJ9.eyJzdWIiOiJ1cm46ZmRjOmdvdi51azoyMDIyOkpHMFJKSTFwWWJuYW5idlBzLWo0ajUtYS1QRmNtaHJ5OVF1OU5DRXA1ZDQiLCJuYmYiOjE2NzAzMzY0NDEsImlzcyI6Imh0dHBzOi8vaWRlbnRpdHkuYWNjb3VudC5nb3YudWsvIiwidm90IjoiUDIiLCJleHAiOjE2ODI5NTkwMzEsImlhdCI6MTY4Mjk1ODczMSwidnRtIjoiaHR0cHM6Ly9vaWRjLmFjY291bnQuZ292LnVrL3RydXN0bWFyayIsInZjIjp7InR5cGUiOlsiVmVyaWZpYWJsZUNyZWRlbnRpYWwiLCJWZXJpZmlhYmxlSWRlbnRpdHlDcmVkZW50aWFsIl0sImNyZWRlbnRpYWxTdWJqZWN0Ijp7Im5hbWUiOlt7Im5hbWVQYXJ0cyI6W3sidmFsdWUiOiJKYW5lIiwidHlwZSI6IkdpdmVuTmFtZSJ9LHsidmFsdWUiOiJXcmlnaHQiLCJ0eXBlIjoiRmFtaWx5TmFtZSJ9XSwidmFsaWRGcm9tIjoiMjAxOS0wNC0wMSJ9LHsibmFtZVBhcnRzIjpbeyJ2YWx1ZSI6IkphbmUiLCJ0eXBlIjoiR2l2ZW5OYW1lIn0seyJ2YWx1ZSI6IldyaWdodCIsInR5cGUiOiJGYW1pbHlOYW1lIn1dLCJ2YWxpZFVudGlsIjoiMjAxOS0wNC0wMSJ9XSwiYmlydGhEYXRlIjpbeyJ2YWx1ZSI6IjE5ODktMDctMDYifV19fSwiYXVkIjoiaXB2QXVkaWVuY2UifQ.qf0yp7B1an7cEwBui7GFCF9NNCJhHxTZuMSh5ehZPmZ4J527okK3pRgdSpWX8DlBFiZS-rXA496egfcfI-neGQ # pragma: allowlist secret
        token_type:
          type: string
          example: Bearer
        expires_in:
          type: integer
          format: int32
          example: 3600
      required: [access_token, token_type, expires_in]

    JourneyOutcome:
      type: object
      description: Provides the outcomes of the Account Component journeys undertaken by the user
      properties:
        sub:
          description: The internal pairwise identifier of the user
          type: string
          example: urn:fdc:gov.uk:2022:JG0RJI1pYbnanbvPs-j4j5-a-PFcmhry9Qu9NCEp5d4
        outcome:
          type: array
          minItems: 1
          items:
            type: object
            description: The outcome of a journey
            example:
              account-delete: true
              timestamp: 1760718467
        email:
          type: string
          format: email
          example: someone@something.com
      required: [sub, email, outcome]

    JWK:
      type: object
      description: JSON Web Key (public parameters only)
      properties:
        kty:
          type: string
          example: RSA
        use:
          type: string
          enum: [sig, enc]
        kid:
          type: string
        alg:
          type: string
          example: RS256
        n:
          type: string
          description: Base64url-encoded modulus for RSA
        e:
          type: string
          description: Base64url-encoded exponent for RSA
        crv:
          type: string
          description: Curve name for EC keys
        x:
          type: string
          description: EC/OKP x coordinate
        y:
          type: string
          description: EC y coordinate
      required: [kty, kid]

    JWKSet:
      type: object
      properties:
        keys:
          type: array
          items:
            $ref: "#/components/schemas/JWK"
      required: [keys]

    ProviderConfiguration:
      type: object
      description: Subset of OIDC Discovery 1.0 metadata
      properties:
        issuer:
          type: string
          format: uri
        authorization_endpoint:
          type: string
          format: uri
        token_endpoint:
          type: string
          format: uri
        jwks_uri:
          type: string
          format: uri
        response_types_supported:
          type: array
          items:
            type: string
        token_endpoint_auth_methods_supported:
          type: array
          items:
            type: string
        token_endpoint_auth_signing_alg_values_supported:
          type: array
          items:
            type: string
        scopes_supported:
          type: array
          items:
            type: string
        grant_types_supported:
          type: array
          items:
            type: string
      required:
        - issuer
        - authorization_endpoint
        - token_endpoint
        - jwks_uri
