AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    Description: >
      The environment type
    AllowedValues:
      - "dev"
      - "build"
      - "staging"
      - "integration"
      - "production"
  CodeSigningConfigArn:
    Type: String
    Description: >
      The ARN of the Code Signing Config to use, provided by the deployment pipeline
    Default: "none"
  PermissionsBoundary:
    Type: String
    Description: >
      The ARN of the permissions boundary to apply to any role created by the template, provided by the deployment pipeline
    Default: "none"
  VpcStackName:
    Type: String
    Description: >
      The name of the stack that defines the VPC in which resources will be located, provided by the deployment pipeline
  CoreStackName:
    Type: String
    Default: "components-core"
  LambdaDeploymentPreference:
    Description: Specifies the configuration to enable gradual Lambda deployments. It can be used to set deployment type and also allows skipping canary deployment by setting to 'AllAtOnce'
    Type: String
    Default: "Canary10Percent10Minutes"
    AllowedValues:
      - AllAtOnce
      - Canary10Percent5Minutes
      - Canary10Percent10Minutes
      - Canary10Percent15Minutes
      - Canary10Percent30Minutes

Mappings:
  EnvironmentConfiguration:
    dev:
      dynatraceSecretArn: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceNonProductionVariables # pragma: allowlist-secret
      rootCookieDomain: dev.account.gov.uk
      frontendDomain: manage.dev.account.gov.uk
      LambdaLogLevel: DEBUG
      UseCanary: false
      apiSessionCookieDomain: manage.dev.account.gov.uk
      authorizeEndpointUrl: https://api.manage.dev.account.gov.uk/authorize
      authFrontendUrl: https://signin.dev.account.gov.uk
      analyticsCookieDomain: dev.account.gov.uk
    build:
      dynatraceSecretArn: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceNonProductionVariables # pragma: allowlist-secret
      rootCookieDomain: build.account.gov.uk
      frontendDomain: manage.build.account.gov.uk
      LambdaLogLevel: INFO
      UseCanary: false
      apiSessionCookieDomain: manage.build.account.gov.uk
      authorizeEndpointUrl: https://api.manage.build.account.gov.uk/authorize
      authFrontendUrl: https://signin.build.account.gov.uk
      analyticsCookieDomain: build.account.gov.uk
    staging:
      dynatraceSecretArn: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceNonProductionVariables # pragma: allowlist-secret
      rootCookieDomain: staging.account.gov.uk
      frontendDomain: manage.staging.account.gov.uk
      LambdaLogLevel: INFO
      UseCanary: true
      apiSessionCookieDomain: manage.staging.account.gov.uk
      authorizeEndpointUrl: https://api.manage.staging.account.gov.uk/authorize
      authFrontendUrl: https://signin.staging.account.gov.uk
      analyticsCookieDomain: staging.account.gov.uk
    integration:
      dynatraceSecretArn: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceNonProductionVariables # pragma: allowlist-secret
      rootCookieDomain: integration.account.gov.uk
      frontendDomain: manage.integration.account.gov.uk
      LambdaLogLevel: INFO
      UseCanary: true
      apiSessionCookieDomain: manage.integration.account.gov.uk
      authorizeEndpointUrl: https://api.manage.integration.account.gov.uk/authorize
      authFrontendUrl: https://signin.integration.account.gov.uk
      analyticsCookieDomain: integration.account.gov.uk
    production:
      dynatraceSecretArn: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceProductionVariables # pragma: allowlist-secret
      rootCookieDomain: account.gov.uk
      frontendDomain: manage.account.gov.uk
      LambdaLogLevel: INFO
      UseCanary: true
      apiSessionCookieDomain: manage.account.gov.uk
      authorizeEndpointUrl: https://api.manage.account.gov.uk/authorize
      authFrontendUrl: https://signin.account.gov.uk
      analyticsCookieDomain: account.gov.uk

Conditions:
  UseCodeSigning:
    Fn::Not:
      - Fn::Equals:
          - !Ref CodeSigningConfigArn
          - "none"
  UsePermissionsBoundary:
    Fn::Not:
      - Fn::Equals:
          - !Ref PermissionsBoundary
          - "none"
  CanariesEnabled: !Equals
    - !FindInMap [EnvironmentConfiguration, !Ref Environment, UseCanary]
    - true

Globals:
  Function:
    DeploymentPreference:
      Type: !If
        - CanariesEnabled
        - !Ref LambdaDeploymentPreference
        - AllAtOnce
      Alarms: []
      Role: !GetAtt CodeDeployServiceRole.Arn
    Tracing: Active
    AutoPublishAlias: live
    KmsKeyArn: !Sub "{{resolve:ssm:/${CoreStackName}/LambdaEnvironmentVariableEncryptionKeyArn}}"
    Layers:
      - arn:aws:lambda:eu-west-2:216552277552:layer:Dynatrace_OneAgent_1_313_2_20250404-043044_with_collector_nodejs:1
    CodeSigningConfigArn: !If
      - UseCodeSigning
      - !Ref CodeSigningConfigArn
      - !Ref AWS::NoValue
    PermissionsBoundary: !If
      - UsePermissionsBoundary
      - !Ref PermissionsBoundary
      - !Ref AWS::NoValue
    VpcConfig:
      SubnetIds:
        - Fn::ImportValue: !Sub ${VpcStackName}-PrivateSubnetIdA
        - Fn::ImportValue: !Sub ${VpcStackName}-PrivateSubnetIdB
        - Fn::ImportValue: !Sub ${VpcStackName}-PrivateSubnetIdC
      SecurityGroupIds:
        - Fn::ImportValue: !Sub ${VpcStackName}-AWSServicesEndpointSecurityGroupId
    Timeout: 10
    MemorySize: 2048
    Architectures:
      - arm64
    Runtime: nodejs22.x
    CodeUri: dist
    Handler: lambda.handler
    Environment:
      Variables:
        POWERTOOLS_LOG_LEVEL:
          !FindInMap [
            EnvironmentConfiguration,
            !Ref Environment,
            LambdaLogLevel,
          ]
        POWERTOOLS_SERVICE_NAME: !Ref AWS::StackName
        AWS_XRAY_CONTEXT_MISSING: IGNORE_ERROR
        ENVIRONMENT: !Ref Environment
        NODE_ENV: "production"
        AWS_LAMBDA_EXEC_WRAPPER: /opt/dynatrace
        DT_CONNECTION_AUTH_TOKEN: !Sub
          - "{{resolve:secretsmanager:${SecretArn}:SecretString:DT_CONNECTION_AUTH_TOKEN}}" # pragma: allowlist-secret
          - SecretArn:
              !FindInMap [
                EnvironmentConfiguration,
                !Ref Environment,
                dynatraceSecretArn,
              ]
        DT_CONNECTION_BASE_URL: !Sub
          - "{{resolve:secretsmanager:${SecretArn}:SecretString:DT_CONNECTION_BASE_URL}}" # pragma: allowlist-secret
          - SecretArn:
              !FindInMap [
                EnvironmentConfiguration,
                !Ref Environment,
                dynatraceSecretArn,
              ]
        DT_CLUSTER_ID: !Sub
          - "{{resolve:secretsmanager:${SecretArn}:SecretString:DT_CLUSTER_ID}}" # pragma: allowlist-secret
          - SecretArn:
              !FindInMap [
                EnvironmentConfiguration,
                !Ref Environment,
                dynatraceSecretArn,
              ]
        DT_LOG_COLLECTION_AUTH_TOKEN: !Sub
          - "{{resolve:secretsmanager:${SecretArn}:SecretString:DT_LOG_COLLECTION_AUTH_TOKEN}}" # pragma: allowlist-secret
          - SecretArn:
              !FindInMap [
                EnvironmentConfiguration,
                !Ref Environment,
                dynatraceSecretArn,
              ]
        DT_TENANT: !Sub
          - "{{resolve:secretsmanager:${SecretArn}:SecretString:DT_TENANT}}" # pragma: allowlist-secret
          - SecretArn:
              !FindInMap [
                EnvironmentConfiguration,
                !Ref Environment,
                dynatraceSecretArn,
              ]
        DT_LOGGING_NODEJS_FLAGS: Exporter=true,LambdaSensor=false
        DT_OPEN_TELEMETRY_ENABLE_INTEGRATION: true
        DT_OPEN_TELEMETRY_ALLOW_EXPLICIT_PARENT: true

Resources:
  CodeDeployServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - codedeploy.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRoleForLambda
      PermissionsBoundary:
        !If [
          UsePermissionsBoundary,
          !Ref PermissionsBoundary,
          !Ref AWS::NoValue,
        ]

  SecretsEncryptionKey:
    Type: AWS::KMS::Key
    Properties:
      EnableKeyRotation: true
      KeyPolicy:
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"

  SecretsEncryptionKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub "alias/${AWS::StackName}-SecretsEncryptionKey"
      TargetKeyId: !GetAtt SecretsEncryptionKey.Arn

  SessionSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      GenerateSecretString:
        PasswordLength: 64
      KmsKeyId: !Ref SecretsEncryptionKey

  SessionsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TableName: !Sub ${AWS::StackName}-SessionStore
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      TimeToLiveSpecification:
        AttributeName: "expires"
        Enabled: true
      BillingMode: PAY_PER_REQUEST
      ContributorInsightsSpecification:
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      SSESpecification:
        KMSMasterKeyId: !Sub "{{resolve:ssm:/${CoreStackName}/DynamoDbSSEKeyArn}}"
        SSEEnabled: true
        SSEType: KMS
      TableClass: STANDARD

  FrontendApiDomain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName:
        !FindInMap [EnvironmentConfiguration, !Ref Environment, frontendDomain]
      RegionalCertificateArn:
        Fn::ImportValue: certificate-CertificateARN
      EndpointConfiguration:
        Types:
          - REGIONAL
      SecurityPolicy: TLS_1_2

  FrontendApiOriginRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Sub
        - "origin.${BaseAlias}"
        - BaseAlias:
            !FindInMap [
              EnvironmentConfiguration,
              !Ref Environment,
              frontendDomain,
            ]
      Type: A
      HostedZoneId:
        Fn::ImportValue: hosted-zone-HostedZoneID
      AliasTarget:
        DNSName: !GetAtt FrontendApiDomain.RegionalDomainName
        HostedZoneId: !GetAtt FrontendApiDomain.RegionalHostedZoneId
        EvaluateTargetHealth: false

  FrontendApiWafAssociation:
    Type: "AWS::WAFv2::WebACLAssociation"
    Properties:
      WebACLArn:
        Fn::ImportValue: "cloudfront-main-CloakingOriginWebACLArn"
      ResourceArn: !Sub "arn:aws:apigateway:${AWS::Region}::/restapis/${FrontendApiGateway}/stages/${Environment}"
    DependsOn:
      - FrontendApiGatewayStage # This resource is created as part of the RestApi resource

  FrontendDomainRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Name:
        !FindInMap [EnvironmentConfiguration, !Ref Environment, frontendDomain]
      Type: A
      HostedZoneId:
        Fn::ImportValue: hosted-zone-HostedZoneID
      AliasTarget:
        DNSName:
          Fn::ImportValue: "cloudfront-main-DistributionDomain"
        HostedZoneId: "Z2FDTNDATAQYW2"
        EvaluateTargetHealth: false

  FrontendApiMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref FrontendApiDomain
      RestApiId: !Ref FrontendApiGateway
      Stage: !Ref Environment
    DependsOn:
      - FrontendApiGatewayStage # This resource is created as part of the RestApi resource

  FrontendApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      AlwaysDeploy: true
      DisableExecuteApiEndpoint: true
      TracingEnabled: true
      EndpointConfiguration:
        Type: REGIONAL
      BinaryMediaTypes:
        - "*/*"

  FrontendLambda:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      LoggingConfig:
        LogGroup: !Ref FrontendLambdaLogGroup
      Events:
        Root:
          Type: Api
          Properties:
            Method: ANY
            Path: /
            RestApiId: !Ref FrontendApiGateway
        CatchAll:
          Type: Api
          Properties:
            Method: ANY
            Path: /{proxy+}
            RestApiId: !Ref FrontendApiGateway
      Environment:
        Variables:
          SESSIONS_SIGNER: !Sub "{{resolve:secretsmanager:${SessionSecret}:SecretString}}"
          SESSIONS_TABLE_NAME: !Sub ${AWS::StackName}-SessionStore
          ROOT_COOKIE_DOMAIN:
            !FindInMap [
              EnvironmentConfiguration,
              !Ref Environment,
              rootCookieDomain,
            ]
          API_SESSION_COOKIE_DOMAIN:
            !FindInMap [
              EnvironmentConfiguration,
              !Ref Environment,
              apiSessionCookieDomain,
            ]
          API_SESSIONS_TABLE_NAME: !Sub "{{resolve:ssm:/${CoreStackName}/ApiSessionsTableName}}"
          AUTH_CODE_TABLE_NAME: !Sub "{{resolve:ssm:/${CoreStackName}/AuthCodeTableName}}"
          JOURNEY_OUTCOME_TABLE_NAME: !Sub "{{resolve:ssm:/${CoreStackName}/JourneyOutcomeTableName}}"
          AUTHORIZE_ENDPOINT_URL:
            !FindInMap [
              EnvironmentConfiguration,
              !Ref Environment,
              authorizeEndpointUrl,
            ]
          AUTH_FRONTEND_URL:
            !FindInMap [
              EnvironmentConfiguration,
              !Ref Environment,
              authFrontendUrl,
            ]
          ANALYTICS_COOKIE_DOMAIN:
            !FindInMap [
              EnvironmentConfiguration,
              !Ref Environment,
              analyticsCookieDomain,
            ]
      Policies:
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:DescribeTable
                - dynamodb:PutItem
                - dynamodb:DeleteItem
                - dynamodb:GetItem
                - dynamodb:Scan
                - dynamodb:UpdateItem
              Resource: !GetAtt SessionsTable.Arn
            - Effect: Allow
              Action:
                - dynamodb:DeleteItem
                - dynamodb:GetItem
              Resource: !Sub "{{resolve:ssm:/${CoreStackName}/ApiSessionsTableArn}}"
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource:
                - !Sub "{{resolve:ssm:/${CoreStackName}/AuthCodeTableArn}}"
                - !Sub "{{resolve:ssm:/${CoreStackName}/JourneyOutcomeTableArn}}"
            - Effect: Allow
              Action:
                - kms:Decrypt
                - kms:GenerateDataKey
              Resource: !Sub "{{resolve:ssm:/${CoreStackName}/DynamoDbSSEKeyArn}}"
            - Effect: Allow
              Action:
                - appconfig:GetLatestConfiguration
                - appconfig:StartConfigurationSession
              Resource: !Sub arn:aws:appconfig:${AWS::Region}:${AWS::AccountId}:application/*

  FrontendLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/lambda/${AWS::StackName}/FrontendLambda"
      RetentionInDays: 30
      KmsKeyId: !Sub "{{resolve:ssm:/${CoreStackName}/CloudWatchEncryptionKeyArn}}"
