# Despite what SonarQube says both the tag and sha digest are needed:
# the digest pins the exact image for reproducibility,
# the tag allows Dependabot to evaluate version constraints
FROM floci/floci:latest@sha256:794407b5deee9b7a10d8ecc1af5296ed95b0c735df5406708440bc0b0c46839d

USER floci

HEALTHCHECK NONE
