# Despite what SonarQube says both the tag and sha digest are needed:
# the digest pins the exact image for reproducibility,
# the tag allows Dependabot to evaluate version constraints
FROM floci/floci:latest@sha256:bf33785b8b79f31175f1deb5c698aa7d5ccbd52f5c3f4649331bad6d6626222a

USER floci

HEALTHCHECK NONE
