name: Check

permissions: {}

on:
  pull_request:
  merge_group:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      packages: read

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - name: Check GitHub Actions
        uses: zizmorcore/zizmor-action@b1d7e1fb5de872772f31590499237e7cce841e8e

      - name: Set up Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version-file: .nvmrc

      - name: Set up tflint
        uses: terraform-linters/setup-tflint@b480b8fcdaa6f2c577f8e4fa799e89e756bb7c93

      - name: Set up SAM CLI
        uses: aws-actions/setup-sam@f84ec7d548307efafe33230528756de3c5841a17
        with:
          use-installer: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JSON Schema CLI
        uses: sourcemeta/jsonschema@f327b8202c5d05fd5f9e309bedf38cd8ddf07ef6

      - name: Set up cfn-lint
        uses: scottbrenner/cfn-lint-action@ed184e91f5085a2932501da8314e899e5e0ef5be

      - name: Install dependencies
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run install-all

      - name: Build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build:all

      - name: Check types
        run: npm run check-types

      - name: ESLint
        run: npm run eslint

      - name: Lint Terraform
        run: npm run tflint

      - name: SAM validate
        run: npm run sam-validate

      - name: Lint CloudFormation
        run: npm run cfnlint

      - name: Check formatting
        run: npm run format

      - name: Knip
        run: npm run knip

      - name: Validate config
        run: npm run config:validate

      - name: Validate API Specs
        run: npm run api-specs:validate

      - name: Validate passkeys convenience metadata
        run: |
          npx tsx -e '
            import { getAllPasskeyConvenienceMetadata } from "./solutions/commons/utils/passkeysConvenienceMetadata/index.ts";

            getAllPasskeyConvenienceMetadata().then((metadata) => {
              console.log("Metadata is valid");
            }).catch((err: unknown) => {
              throw err
            });
          '
