name: Check

permissions: {}

on:
  pull_request:
  merge_group:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - name: Check GitHub Actions
        uses: zizmorcore/zizmor-action@b1d7e1fb5de872772f31590499237e7cce841e8e

      - name: Set up Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version-file: .nvmrc

      - name: Set up tflint
        uses: terraform-linters/setup-tflint@b480b8fcdaa6f2c577f8e4fa799e89e756bb7c93

      - name: Set up SAM CLI
        uses: aws-actions/setup-sam@f84ec7d548307efafe33230528756de3c5841a17
        with:
          use-installer: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JSON Schema CLI
        uses: sourcemeta/jsonschema@de5d93249013195a09f88e8fc8ff836412c544d0

      - name: Set up cfn-lint
        uses: scottbrenner/cfn-lint-action@9636da81fb2e0cef75725d8dda11b0148940b7ae

      - name: Install dependencies
        env:
          GITHUB_NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run install-all

      - name: Install integration tests dependencies
        run: cd solutions/integration-tests && npm ci

      - name: Check types
        run: npm run check-types

      - name: ESLint
        run: npm run eslint

      - name: Lint Terraform
        run: npm run tflint

      - name: SAM validate frontend
        run: npm run sam-validate:frontend

      - name: SAM validate API
        run: npm run sam-validate:api

      - name: SAM validate stubs
        run: npm run sam-validate:stubs

      - name: SAM validate core
        run: npm run sam-validate:core

      - name: Lint CloudFormation
        run: npm run cfnlint

      - name: Check formatting
        run: npm run format

      - name: Knip
        run: npm run knip

      - name: Validate config
        run: npm run config:validate

      - name: Validate API Specs
        run: npm run api-specs:validate

      - name: Build core
        run: npm run build:core

      - name: Build frontend
        run: npm run build:frontend

      - name: Build stubs
        run: npm run build:stubs

      - name: Build API
        run: npm run build:api

      - name: Validate passkeys convenience metadata
        run: |
          npx tsx -e '
            import { getAllPasskeyConvenienceMetadata } from "./solutions/commons/utils/passkeysConvenienceMetadata/index.ts";

            getAllPasskeyConvenienceMetadata().then((metadata) => {
              console.log("Metadata is valid");
            }).catch((err: unknown) => {
              throw err
            });
          '
