name: Deploy Application

permissions: {}

on:
  push:
    branches:
      - main
    paths:
      - solutions/app-infra/**
      - solutions/frontend/**
      - solutions/api/**
      - solutions/core/**
      - solutions/stubs/**
      - solutions/commons/**
      - solutions/integration-tests/**
      - .github/workflows/deploy.yaml
      - package.json
      - package-lock.json
      - .npmrc
      - .nvmrc
      - tsconfig.json

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  publish-integration-tests-image:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false

      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c
        with:
          role-to-assume: ${{ secrets.PIPELINE_GH_ACTIONS_ROLE_ARN }}
          aws-region: "eu-west-2"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@03f1aad4c6c7ffd436567f42f9384779290529bd

      - name: Build & publish Docker image
        working-directory: solutions/integration-tests
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.POST_DEPLOY_TESTS_IMAGE_REPOSITORY }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push -a $ECR_REGISTRY/$ECR_REPOSITORY

  deploy:
    needs: publish-integration-tests-image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: read

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false

      - name: Set up Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version-file: .nvmrc

      - name: Set up SAM CLI
        uses: aws-actions/setup-sam@89ddb14d60e682855e3fea4be85b3c56485de310
        with:
          use-installer: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c
        with:
          role-to-assume: ${{ secrets.PIPELINE_GH_ACTIONS_ROLE_ARN }}
          aws-region: "eu-west-2"

      - name: Install dependencies
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run install-all

      - name: Build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build:all

      - name: Test
        run: npm run test:coverage

      - name: Deploy
        uses: govuk-one-login/devplatform-upload-action@ec09f4b1f8648fe21dd18a40a2d8e2fa94d0ad41
        with:
          artifact-bucket-name: ${{ secrets.PIPELINE_SOURCE_BUCKET_NAME }}
          signing-profile-name: ${{ secrets.SIGNING_PROFILE_NAME }}
          working-directory: ./solutions/app-infra
          template-file: .aws-sam/build/template.yaml
