name: Deploy config to dev

on:
  workflow_dispatch:
    inputs:
      refType:
        type: choice
        description: "Find branch name, commit SHA, or tag?"
        options:
          - Branch name
          - Commit SHA
          - Tag
        default: Branch name
      gitRef:
        description: "Input branch name, commit SHA, or tag"
        required: true
        type: string
        default: main

jobs:
  deploy-config-to-dev:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          persist-credentials: false
          ref: ${{ inputs.gitRef }}

      - name: Set commit SHA
        if: github.event.inputs.refType == 'Commit SHA'
        run: echo GIT_REF_SHA=${GIT_REF} >> $GITHUB_ENV
        env:
          GIT_REF: ${{ inputs.gitRef }}

      - name: Set commit SHA by branch name
        if: github.event.inputs.refType == 'Branch name'
        run: echo GIT_REF_SHA=$(git log -1 ${GIT_REF} --pretty=format:%H) >> $GITHUB_ENV
        env:
          GIT_REF: ${{ inputs.gitRef }}

      - name: Set commit SHA by tag
        if: github.event.inputs.refType == 'Tag'
        run: echo GIT_REF_SHA=$(git rev-list -n 1 ${GIT_REF}) >> $GITHUB_ENV
        env:
          GIT_REF: ${{ inputs.gitRef }}

      - name: Set tag
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Set current datetime
        run: echo "date=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_OUTPUT

      - name: Assume AWS Role
        uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          role-to-assume: ${{ secrets.GHA_CONFIG_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Sign and Zip config file
        env:
          CONFIG_FILE: config.json
          ARTEFACT_SIGNING_KEY_ARN: ${{ secrets.GHA_CONFIG_SIGNING_KEY_ARN }}
        run: |
          aws kms sign \
            --key-id "${ARTEFACT_SIGNING_KEY_ARN}" \
            --message "$(openssl dgst -sha256 -binary "${CONFIG_FILE}" | base64)" \
            --message-type DIGEST \
            --signing-algorithm ECDSA_SHA_256 \
            --region eu-west-2 > "config/${CONFIG_FILE}.sig"
          zip -j config.zip "${CONFIG_FILE}" "${CONFIG_FILE}.sig"

      - name: Push config file to AWS S3 Bucket
        if: env.CONFIG_SOURCE_BUCKET_NAME
        env:
          CONFIG_SOURCE_BUCKET_NAME: ${{ secrets.GHA_CONFIG_ARTIFACT_BUCKET }}
          CONFIG_FILE: config.json
          ENVIRONMENT: build # Note: this must match the environment name configured in the AppConfig pipeline
        run: |
          aws s3api put-object \
          --bucket "$CONFIG_SOURCE_BUCKET_NAME" \
          --key "$ENVIRONMENT"/config.zip \
          --body config.zip
